@url = http://localhost:3000


###

# @name createCategory
POST {{url}}/api/categories HTTP/1.1
Content-Type: application/json

{
  "name": "Clothes",
  "image": "https://fastly.picsum.photos/id/491/200/300.jpg?hmac=1uGno3XFc0HqGY5bM9-mMu0M_wwx7oC0bC1hj_a9p04",
  "banner": "https://fastly.picsum.photos/id/491/200/300.jpg?hmac=1uGno3XFc0HqGY5bM9-mMu0M_wwx7oC0bC1hj_a9p04"
}

###

# @name getCategories
GET {{url}}/api/categories HTTP/1.1
